
package csi;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class humanResourceDashboard extends javax.swing.JFrame {

    /**
     * Creates new form humanResourceDashboard
     */
    public humanResourceDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuOption = new javax.swing.JPopupMenu();
        newEmployee = new javax.swing.JMenuItem();
        newDepartment = new javax.swing.JMenuItem();
        newDesignation = new javax.swing.JMenuItem();
        dashboard = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        parent = new javax.swing.JLayeredPane();
        home = new javax.swing.JPanel();
        onboarding = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        comboboxDepartment = new javax.swing.JComboBox<>();
        comboboxDesignation = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboboxSex = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        newEmployee.setText("Employee");
        popupMenuOption.add(newEmployee);

        newDepartment.setText("Department");
        popupMenuOption.add(newDepartment);

        newDesignation.setText("Designation");
        popupMenuOption.add(newDesignation);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dashboard.setBackground(new java.awt.Color(255, 255, 255));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(66, 133, 244));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("New Employee");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        dashboard.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 158, -1));

        jButton4.setBackground(new java.awt.Color(66, 133, 244));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Log Out");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        dashboard.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 158, -1));

        parent.setLayout(new java.awt.CardLayout());

        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        parent.add(home, "card2");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("First Name");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, -1, -1));
        jPanel4.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, 117, -1));
        jPanel4.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 102, 117, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 76, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, 252, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Contact");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 183, -1, -1));

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 208, 170, -1));

        txtContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 210, 226, -1));

        comboboxDepartment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboboxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Human Resource", "Finance", "Marketing", "IT", " " }));
        comboboxDepartment.setSelectedIndex(-1);
        jPanel4.add(comboboxDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 291, 140, -1));

        comboboxDesignation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboboxDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Executive", "Intern", " " }));
        comboboxDesignation.setSelectedIndex(-1);
        jPanel4.add(comboboxDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 252, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Department");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 294, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Designation");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 255, 74, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Sex");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 76, -1, -1));

        comboboxSex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboboxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer Not to Answer", " ", " " }));
        comboboxSex.setSelectedIndex(-1);
        jPanel4.add(comboboxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 99, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Salary");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 183, -1, -1));

        btnSave.setBackground(new java.awt.Color(66, 133, 244));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 74, -1));

        btnCancel.setBackground(new java.awt.Color(66, 133, 244));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Password");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 129, 74, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 156, 174, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Address");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 335, -1, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 362, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("ONBOARDING");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 13, -1, -1));

        jButton5.setBackground(new java.awt.Color(66, 133, 244));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Go Back");
        jButton5.setToolTipText("");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout onboardingLayout = new javax.swing.GroupLayout(onboarding);
        onboarding.setLayout(onboardingLayout);
        onboardingLayout.setHorizontalGroup(
            onboardingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        onboardingLayout.setVerticalGroup(
            onboardingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        parent.add(onboarding, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(766, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         humanResourceOperation hro = new humanResourceOperation(txtFirstName, txtLastName, txtEmail, txtContact, txtSalary, txtAddress,
                comboboxSex, comboboxDesignation, comboboxDepartment, txtPassword);
        try {

            boolean isSuccess = hro.insertRecords();

            if (isSuccess) {
                JOptionPane.showMessageDialog(null, "Record inserted successfully!");
                hro.resetForm();//cleat the feilds

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An Error Occured,Please Try again");
            hro.resetForm();
        }
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        int response = JOptionPane.showConfirmDialog(this, "Are you to Log Out");

        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            new userLogin().setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parent.removeAll();
        parent.add(onboarding);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        parent.removeAll();
        parent.add(home);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       
        int response = JOptionPane.showConfirmDialog(this, "Are you sure to cancel? current information will be deleted");
        if (response == JOptionPane.YES_OPTION) {

            humanResourceOperation hro = new humanResourceOperation(txtFirstName, txtLastName, txtEmail, txtContact, txtSalary, txtAddress, comboboxSex, comboboxDesignation, comboboxDepartment, txtPassword);
            hro.resetForm();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new humanResourceDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboboxDepartment;
    private javax.swing.JComboBox<String> comboboxDesignation;
    private javax.swing.JComboBox<String> comboboxSex;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem newDepartment;
    private javax.swing.JMenuItem newDesignation;
    private javax.swing.JMenuItem newEmployee;
    private javax.swing.JPanel onboarding;
    private javax.swing.JLayeredPane parent;
    private javax.swing.JPopupMenu popupMenuOption;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
